# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Help: https://starship.rs/config/

# Inserts a blank line between shell prompts
add_newline = false

# minimal left prompt
format = """$directory$character"""
palette = "catppuccin_mocha"
# rest of prompt on right
right_format = """$all"""

[directory]
truncation_symbol = "…/"
truncate_to_repo = true

[cmd_duration]
min_time = 3_000
show_milliseconds = true
style = "bold yellow"
# if a command takes too long, show notification
#show_notifications = true
min_time_to_notify = 10_000

[sudo]
disabled = false

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
